---
title: "Homer Theme"
subtitle: "Walkx"
logo: "logo.png"

header: false
footer: '<p>Theme made with <span class="has-text-danger">❤️</span> by <a href="https://github.com/WalkxCode">Walkx</a></p>' # Set false if you want to hide it.

stylesheet:
  - "assets/custom.css"

columns: "4" # You can change this to making sub changes any number that is a factor of 12: (1, 2, 3, 4, 6, 12)
theme: default
colors:
  light:
    highlight-primary: "#fff5f2"
    highlight-secondary: "#fff5f2"
    highlight-hover: "#bebebe"
    background: "#12152B"
    card-background: "rgba(255, 245, 242, 0.8)"
    text: "#ffffff"
    text-header: "#fafafa"
    text-title: "#000000"
    text-subtitle: "#111111"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#3273dc"
    link-hover: "#2e4053"
    background-image: "../assets/wallpaper-light.jpeg" # Change wallpaper.jpeg to the name of your own custom wallpaper!
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "rgba(24, 28, 58, 0.8)"
    text: "#eaeaea"
    text-header: "#7C71DD"
    text-title: "#fafafa"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#c1c1c1"
    link-hover: "#fafafa"
    background-image: "../assets/wallpaper.jpeg"

services:
  - name: "Server Management"
    icon: "fa fa-window-maximize"
    items:
      - name: "Esxi1"
        logo: "assets/tools/esxi.png"
        subtitle: "VM1 management"
        url: "http://192.168.1.20"       
      - name: "Portainer"
        logo: "assets/tools/portainer.png"
        subtitle: "(OMV Server) Syncthing"
        url: "http://192.168.1.16:9000"
        target: "_blank" # optional html a tag target attribute
      - name: "Portainer"
        logo: "assets/tools/portainer.png"
        subtitle: "(Bitwarden Server) Bitwarden,Trillium"
        url: "http://192.168.1.35:9000/"      
      - name: "Portainer"
        logo: "assets/tools/portainer.png"
        subtitle: "(Plex Server) Calibre-Web,Code-Server"
        url: "http://192.168.1.19:9000"
        target: "_blank" # optional html a tag target attribute
      - name: "HP Printer"
        logo: "assets/tools/printer.png"
        subtitle: "Printer config page"
        url: "http://192.168.1.107"               
  - name: "Applications"
    icon: "fa fa-window-maximize"
    items:
      - name: "Bitwarden"
        logo: "assets/tools/bitwarden.png"
        subtitle: "Password Management"
        url: "https://192.168.1.35"
      - name: "Uptime Kuma"
        logo: "assets/tools/kuma.png"
        subtitle: "Status Check"
        url: "http://192.168.1.35:3001/dashboard"   
      - name: "Octoprint"
        logo: "assets/tools/octoprint.png"
        subtitle: "Ender"
        url: "http://192.168.1.2"
  - name: "Media Management"
    icon: "fa fa-window-maximize"
    items:
      - name: "Sonarr"
        logo: "assets/tools/sonarr.png"
        url: "http://192.168.1.19:8989"
        subtitle: "TV Show Mngmnt"
      - name: "Radarr"
        logo: "assets/tools/radarr.png"
        url: "http://192.168.1.19:7878"
        subtitle: "Movie Mngmnt"
      - name: "jackett"
        logo: "assets/tools/jackett.png"
        url: "http://192.168.1.19:9117"
        subtitle: "Indexer Mngmnt"   
      - name: "Overseerr"
        logo: "assets/tools/overseerr.png"
        url: "http://192.168.1.19:5055"
        subtitle: "Request Mngmnt" 
      - name: "Transmission"
        logo: "assets/tools/transmission.png"
        url: "http://192.168.1.19:9091"
        subtitle: "Torrent Mngmnt" 
  - name: "Security"
    icon: "fa fa-window-maximize"
    items:
      - name: "Wazuh"
        logo: "assets/tools/wazuh.png"
        subtitle: "SIEM"
        url: "https://192.168.1.135"
      - name: "Ntop"
        logo: "assets/tools/ntop.png"
        subtitle: "Network Monitoring"
        url: "https://192.168.1.1:3000/"
        target: "_blank" # optional html a tag target attribut
      - name: "Cameras"
        logo: "assets/tools/kasm.png"
        subtitle: "Nest Cam Live Feed"
        url: "https://home.google.com"
        target: "_blank" # optional html a tag target attribut
  - name: "Network"
    icon: "fa-sharp fa-solid fa-ethernet"
    items:
      - name: "Pfsense Router"
        url: "https://192.168.1.1"
        subtitle: "Router & firewall management"
        logo: "assets/tools/pfsense.png"
      - name: "Pi Hole"
        logo: "assets/tools/pihole.png"
        subtitle: "DNS and ad blocker"
        url: "http://192.168.1.45/admin/"
      - name: "Omada"
        logo: "assets/tools/omada.png"
        subtitle: "Device monitoring & management on local network"
        url: "http://192.168.1.135:8088"
  - name: "Media"
    icon: "fa fa-tablet"
    items:
      - name: "Plex"
        logo: "assets/tools/plex.png"
        url: "http://192.168.1.19:32400"
        subtitle: "Plex media server"
      - name: "Calibre-web"
        logo: "assets/tools/calibre.png"
        url: "http://192.168.1.19:8083"
        subtitle: "ebook reader"
      - name: "Draw.io"
        logo: "assets/tools/draw.png"
        url: "http://192.168.1.35:8080"
        subtitle: ""
  - name: "Backups"
    icon: "fa fa-server"
    items:        
      - name: "Open Media Vault"
        logo: "assets/tools/omv.png"
        subtitle: "Backup solution"
        url: "http://192.168.1.16"
      - name: "Syncthing"
        logo: "assets/tools/sync.png"
        subtitle: "File syncronization"
        url: "http://192.168.1.16:8384"
        target: "_blank" # optional html a tag target attribute           
  - name: "Favorites"
    icon: "fa fa-heart"
    items:        
      - name: "TryHackMe"
        logo: "assets/tools/tryhackme.png"
        url: "https://www.Tryhackme.com"
      - name: "ChatGPT"
        logo: "assets/tools/chatgpt.png"
        url: "https://chat.openai.com"

