name: Download File

on:
  schedule:
    - cron: '0 2 * * *'  # Run daily at 2 AM
  workflow_dispatch:  # Allow manual trigger

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download file using wget
        run: |
          URL="https://raw.githubusercontent.com/L0gic77/HomerConfig/main/config.yml?token=GHSAT0AAAAAACTDPLIFKLSCYUNCLMSCXMMKZS5CH7Q"
          DESTINATION="/usr/share/nginx/homer/assets/"
          wget -O "$DESTINATION" "$URL"
          if [ $? -eq 0 ]; then
            echo "File downloaded successfully to $DESTINATION"
          else
            echo "Failed to download file"
            exit 1
          fi
